// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyLearnFuture.Persistence;

#nullable disable

namespace MyLearnFuture.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyLearnFuture.Domain.Entities.ImagesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateBy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ImagesTable");
                });

            modelBuilder.Entity("MyLearnFuture.Domain.Entities.SpacedRepetitionConfigEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateBy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<int>("DurationHours")
                        .HasColumnType("int");

                    b.Property<Guid?>("ImagesEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<Guid?>("SpacedRepetitionConfigEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TopicsEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ImagesEntityId");

                    b.HasIndex("SpacedRepetitionConfigEntityId");

                    b.HasIndex("TopicsEntityId");

                    b.ToTable("SpacedRepetitionConfigTable");
                });

            modelBuilder.Entity("MyLearnFuture.Domain.Entities.TopicsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateBy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TopicsTable");
                });

            modelBuilder.Entity("MyLearnFuture.Domain.Entities.VocabulariesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateBy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Image_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SpacedRepetitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SpacedRepetition_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SpacedRepetition_LastLearn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TopicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Topic_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Transcription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.HasIndex("SpacedRepetitionId");

                    b.HasIndex("TopicId");

                    b.ToTable("VocabulariesTable");
                });

            modelBuilder.Entity("MyLearnFuture.Domain.Entities.SpacedRepetitionConfigEntity", b =>
                {
                    b.HasOne("MyLearnFuture.Domain.Entities.ImagesEntity", null)
                        .WithMany("spacedRepetitionConfigEntities")
                        .HasForeignKey("ImagesEntityId");

                    b.HasOne("MyLearnFuture.Domain.Entities.SpacedRepetitionConfigEntity", null)
                        .WithMany("SpacedRepetitionConfig_VocabulariesEntity")
                        .HasForeignKey("SpacedRepetitionConfigEntityId");

                    b.HasOne("MyLearnFuture.Domain.Entities.TopicsEntity", null)
                        .WithMany("spacedRepetitionConfigEntities")
                        .HasForeignKey("TopicsEntityId");
                });

            modelBuilder.Entity("MyLearnFuture.Domain.Entities.VocabulariesEntity", b =>
                {
                    b.HasOne("MyLearnFuture.Domain.Entities.ImagesEntity", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.HasOne("MyLearnFuture.Domain.Entities.SpacedRepetitionConfigEntity", "SpacedRepetition")
                        .WithMany()
                        .HasForeignKey("SpacedRepetitionId");

                    b.HasOne("MyLearnFuture.Domain.Entities.TopicsEntity", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId");

                    b.Navigation("Image");

                    b.Navigation("SpacedRepetition");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("MyLearnFuture.Domain.Entities.ImagesEntity", b =>
                {
                    b.Navigation("spacedRepetitionConfigEntities");
                });

            modelBuilder.Entity("MyLearnFuture.Domain.Entities.SpacedRepetitionConfigEntity", b =>
                {
                    b.Navigation("SpacedRepetitionConfig_VocabulariesEntity");
                });

            modelBuilder.Entity("MyLearnFuture.Domain.Entities.TopicsEntity", b =>
                {
                    b.Navigation("spacedRepetitionConfigEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
